# See for detail: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true

Bundler/OrderedGems:
  Enabled: true

Style/EmptyLines:
  Enabled: true

Style/TrailingBlankLines:
  Enabled: true

Style/TrailingWhitespace:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent
